---
- name: IAM user add
  hosts: localhost
  vars_files: 
    - var_iam_user_add
  tasks:
    - name: IAM user add with password (console access) 
      iam:
        iam_type: user
        name: "{{ name }}"                    # Type name of the user
        state: present                      
        password: "{{ password }}"            # Create user passwordZZ
